import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.scss'
import React from 'react'
import Landing from '../components/Home/Landing/Landing'
import Therapy from '../components/Home/Therapy/Therapy'
import Share from '../components/Home/Share/Share'
import Thought from '../components/Home/Thought/Thought'
import Counsel from '../components/Home/Counsel/Counsel'
import Philosophy from '../components/Home/Philosophy/Philosophy'
import People from '../components/Home/People/People'
import Footer from '../components/Footer/Footer'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Anonymous Confidant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
      <Landing/>
      <Therapy/>
      <Share/>
      <Thought />
      <Counsel />
      <Philosophy />
      <People />
      <Footer />
      </>
    </div>
  )
}
