
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'


export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'

export const STORY_DETAIL_REQUEST = 'STORY_DETAIL_REQUEST'
export const STORY_DETAIL_SUCCESS = 'STORY_DETAIL_SUCCESS'
export const STORY_DETAIL_FAIL = 'STORY_DETAIL_FAIL'

export const SAVE_STORY_ID = 'SAVE_STORY_ID'
export const STORY_STORY_REQUEST = 'STORY_STORY_REQUEST'

export const THERAPISTS_LIST_REQUEST = 'THERAPISTS_LIST_REQUEST'
export const THERAPISTS_LIST_SUCCESS = 'THERAPISTS_LIST_SUCCESS'
export const THERAPISTS_LIST_FAIL = 'THERAPISTS_LIST_FAIL'


export const THERAPISTS_BOOKING_REQUEST = 'THERAPISTS_BOOKING_REQUEST'
export const THERAPISTS_BOOKING_SAVE_THERAPIST_ID = 'THERAPISTS_BOOKING_SAVE_THERAPIST_ID'
export const THERAPISTS_BOOKING_SAVE_PLAN_ID = 'THERAPISTS_BOOKING_SAVE_PLAN_ID'
export const THERAPISTS_BOOKING_SAVE_RESERVATION_ID = 'THERAPISTS_BOOKING_SAVE_RESERVATION_ID'
export const THERAPISTS_BOOKING_SAVE_REFERENCE_ID = 'THERAPISTS_BOOKING_SAVE_REFERENCE_ID'
export const THERAPISTS_BOOKING_SAVE_SESSION_METADATA = 'THERAPISTS_BOOKING_SAVE_SESSION_METADATA'